### ISSUE TITLE
Authelia user_database.yml

### ISSUE THREAD

**Issue by kireque** [Pumba98/k3s-flux-cluster#437]
Hello,

I am using your repo as inspiration for my own GitOps K3S cluster. 
Many thanks for sharing this repo.

I was wondering what the raw data structure looks like in the user_database.yml file that you use for Authelia?
How did you embed an yml structure in the sops encoded file?

Thanks in advance.

**Comment by Pumba98** [comment]
Hi,

the decrypted file looks like this

```yaml
apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: networking
stringData:
    users_database.yml: |
        ###############################################################
        #                         Users Database                      #
        ###############################################################
        users:
          pumba98:
            displayname: "Pumba98"
            password: "$argon2id$v=...."
            email: mail@pumba98.de
            groups:
              - admins

```

hope this helps!
